### ISSUE TITLE
a mistake

### ISSUE THREAD

**Issue by gaohuag** [nats-io/docs#62]
in authorization.md,

> | Property | Description
> | :------  | :---- |

> | `publish` | subject, list of subjects, or permission map the client can publish |

> | `subscribe` | subject, list of subjects, or permission map the client can **publish** |

should change to:
| Property | Description |
| :------  | :---- |
| `publish` | subject, list of subjects, or permission map the client can publish |
| `subscribe` | subject, list of subjects, or permission map the client can **subscribe** |

**Comment by gcolliso** [comment]
fixed in PR [#64](https://github.com/nats-io/docs/pull/64)
thanks @gaohuag
